# Generated by Django 5.2.17 on 2026-09-10 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='e.g. MH 04 AB 1234', max_length=20, unique=True)),
                ('brand', models.CharField(help_text='e.g. Honda, Tata, Hyundai', max_length=50)),
                ('car_model', models.CharField(help_text='e.g. City, Nexon, i20', max_length=50)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('EV', 'Electric (EV)')], default='Petrol', max_length=20)),
                ('manufacturing_year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField(default=0, help_text='Current KMs driven')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
