# Generated by Django 5.2.17 on 2026-09-11 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('General', 'General Service / Oil Change'), ('Wash', 'Car Wash & Cleaning'), ('AC', 'AC Repair & Gas'), ('Denting', 'Denting & Painting'), ('Custom', 'Other / Custom Issue')], default='General', max_length=20)),
                ('problem_description', models.TextField(blank=True, help_text='Kya problem aa rahi hai?')),
                ('booking_date', models.DateField(help_text='Kis din service ke liye aana hai?')),
                ('status', models.CharField(choices=[('Pending', 'Pending (Wait)'), ('Repairing', 'Repairing (Kaam Chalu)'), ('Ready', 'Ready (Le Jao)'), ('Delivered', 'Delivered (Done)')], default='Pending', max_length=20)),
                ('final_bill', models.PositiveIntegerField(blank=True, help_text='Final amount to pay', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customers.vehicle')),
            ],
        ),
    ]
