# Generated by Django 5.2.17 on 2026-09-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback',
            field=models.TextField(blank=True, help_text='Customer Review', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Rating out of 5', null=True),
        ),
    ]
